# NOTE: update this with your service name
service:
  name: somap-infr-be
  alias: somap
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  photosBucketName: "somapPhotosBucket"
  accountId: ${file(./environment/${self:provider.stage}.environment.json):ACCOUNT_ID}
resources:
  # Cognito
  - ${file(resources/cognito/cognito-user-pool.yml)}
  - ${file(resources/cognito/cognito-identity-pool.yml)}
  # SES Template
  - ${file(resources/ses/template.yml)}
    # S3
    - ${file(resources/s3/s3.yml)}
